apiVersion: apps/v1
kind: Deployment
metadata:
  name: airbnb-app
  labels:
    app: airbnb

spec:
  replicas: 1
  selector:
    matchLabels:
      app: airbnb
  template:
    metadata:
      labels:
        app: airbnb
    spec:
      containers:
        - name: airbnb-container
          image: ankitdockerd/airbnb:v1  
          ports:
          - containerPort: 8080  
          env:
          - name: CLOUD_NAME
            valueFrom:
              secretKeyRef:
                name: airbnb-secret
                key: CLOUD_NAME 

          - name: CLOUD_API_KEY
            valueFrom:
              secretKeyRef:
                name: airbnb-secret
                key: CLOUD_API_KEY 

          - name: CLOUD_API_SECRET
            valueFrom:
              secretKeyRef:
                name: airbnb-secret
                key: CLOUD_API_SECRET 

          - name: ATLASDB_URL
            valueFrom:
              secretKeyRef:
                name: airbnb-secret
                key: ATLASDB_URL

          - name: MAP_TOKEN
            valueFrom:
              secretKeyRef:
                name: airbnb-secret
                key: MAP_TOKEN 

          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: airbnb-secret
                key: SECRET
                                                                                                                                                                     