apiVersion: v1
kind: Secret
metadata:
  name: airbnb-secret
type: Opaque
data:
  CLOUD_NAME: ZGw4bW0yeXBp
  CLOUD_API_KEY: NDk1NDU0NTY5NTU0NTI3
  CLOUD_API_SECRET: WU1Bcjg5Y19oY1YzSGJJWEZrNEM3c0Jmak4w
  ATLASDB_URL: bW9uZ29kYitzcnY6Ly9hbmtpdGR1YmV5OTQzMTk2OTYzOV9kYl91c2VyOkJCREkxeThOUWVlQkNTNnZAY2x1LmxoZmlqejgubW9uZ29kYi5uZXQvP3JldHJ5V3JpdGVzPWZhbHNlJnRscz10cnVlJmFwcE5hbWU9Q2x1
  MAP_TOKEN: cGsuZXlKMUlqb2lZMmh2ZEdrNU5ETXhiR0YwWVNJc0ltRWlPaUpqYkhnek5YQjRhbW93ZHpOMk1tMXpaR1F4TTJObmNUWmtJbjAuZGViNFRfa1k1cE9tZ3U5SzVXbDdkZw==
  SECRET: Ymprd2prYmRzY2tqYmRzY2prYmRj
